runtime: nodejs20
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  NODE_ENV: production
  GOOGLE_CLOUD_PROJECT: "your-project-id"
  CLOUD_STORAGE_BUCKET: "your-storage-bucket"

handlers:
  - url: /_next/static
    static_dir: .next/static
    secure: always

  - url: /static
    static_dir: public
    secure: always

  - url: /.*
    script: auto
    secure: always 