steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['ci']
    dir: '.'

  # Run linting
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'lint']
    dir: '.'

  # Build the application
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    dir: '.'

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - app
      - deploy
      - app.yaml
      - --version=$SHORT_SHA
      - --project=$PROJECT_ID
      - --quiet

# Store build artifacts
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-build-artifacts/'
    paths: ['.next/**/*']

# Build timeout
timeout: '1200s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY 